import React, { useRef, useState, useEffect, useMemo } from 'react';
import { useCaseAnalysisState } from '../useCaseAnalysis';
import { useTextToSpeech } from '@/hooks/useTextToSpeech';
import { useTextSizer } from '@/hooks/useTextSizer';
import { exportElementAsPDF } from '@/utils/exportUtils';
import { getISODate, getFormattedDate } from '@/utils/dateUtils';
import { cleanAnalysisForSpeech } from '@/utils/stringUtils';

import Feedback from '@/features/marketing/components/Feedback';
import LightbulbIcon from '@/components/icons/LightbulbIcon';
import GavelIcon from '@/components/icons/GavelIcon';
import AlertTriangleIcon from '@/components/icons/AlertTriangleIcon';
import FileTextIcon from '@/components/icons/FileTextIcon';
import AnalysisActionsBar from './AnalysisActionsBar';
import AnalysisReferences from './AnalysisReferences';
import SummaryPanel from './SummaryPanel';
import ObligationsPanel from './ObligationsPanel';
import FlagsPanel from './FlagsPanel';
import DetailsPanel from './DetailsPanel';


type AnalysisTab = 'summary' | 'obligations' | 'flags' | 'details';

interface ActionItem {
    item: string;
    deadline?: string;
    source: string;
    completed: boolean;
    isDeleting: boolean;
}

const AnalysisResult: React.FC = () => {
    const { analysisResponse: response, jurisdiction } = useCaseAnalysisState();
    const reportRef = useRef<HTMLDivElement>(null);
    const { isSpeaking, isPaused, speak, cancel, pause, resume } = useTextToSpeech();
    const [isExportingPdf, setIsExportingPdf] = useState(false);
    const [activeTab, setActiveTab] = useState<AnalysisTab>('summary');
    const [renderAllForPdf, setRenderAllForPdf] = useState(false);
    const [isCopied, setIsCopied] = useState(false);
    const [isStrategicEmailEditing, setIsStrategicEmailEditing] = useState(false);
    const [editedStrategicEmail, setEditedStrategicEmail] = useState(response?.strategicCommunication?.draftEmail || '');
    const textSizer = useTextSizer();
    const [actionItems, setActionItems] = useState<ActionItem[]>([]);
    const disclaimerText = 'Disclaimer: This document was created using artificial intelligence and is intended to provide helpful information. It is not a source of legal advice. We recommend that you verify the information for accuracy.';

    // Initialize/Reset action items state when response changes
    useEffect(() => {
        if (response?.actionItems) {
            setActionItems(
                response.actionItems.map(item => ({
                    ...item,
                    completed: false,
                    isDeleting: false,
                }))
            );
        }
    }, [response]);
    
    useEffect(() => {
        if (isCopied) {
            const timer = setTimeout(() => setIsCopied(false), 2000);
            return () => clearTimeout(timer);
        }
    }, [isCopied]);

    useEffect(() => {
        // When the main response changes (e.g., new analysis), reset the email draft and editing state.
        if (response?.strategicCommunication?.draftEmail) {
            setEditedStrategicEmail(response.strategicCommunication.draftEmail);
        } else {
            setEditedStrategicEmail('');
        }
        setIsStrategicEmailEditing(false);
    }, [response]);

    if (!response) {
        return (
            <div className="text-center p-4 text-gray-400">
                <p>No analysis data to display.</p>
            </div>
        );
    }
    
    const handleExportPdf = async () => {
        if (!reportRef.current) return;
        
        setIsExportingPdf(true);
        setRenderAllForPdf(true);

        await new Promise(resolve => setTimeout(resolve, 100));

        try {
            const isoDate = getISODate();
            const friendlyDate = getFormattedDate();
            const filename = `CustodyBuddy-Analysis-${isoDate}.pdf`;
            const headerText = `AI Case Analysis - Generated by CustodyBuddy.com on ${friendlyDate}`;
            await exportElementAsPDF(reportRef.current, filename, headerText);
        } catch (error) {
            console.error("Failed to export PDF:", error);
            alert("Sorry, there was an issue creating the PDF. Please try again.");
        } finally {
            setRenderAllForPdf(false);
            setIsExportingPdf(false);
        }
    };

    const handlePlayPause = () => {
        if (!isSpeaking) {
            const plainText = cleanAnalysisForSpeech(response);
            speak(plainText);
        } else if (isPaused) {
            resume();
        } else {
            pause();
        }
    };

    const handleStop = () => {
        cancel();
    };

    const handleCopyStrategicEmail = () => {
        navigator.clipboard.writeText(editedStrategicEmail);
        setIsCopied(true);
    };

    const handleToggleComplete = (index: number) => {
        setActionItems(prevItems =>
            prevItems.map((item, i) =>
                i === index ? { ...item, completed: !item.completed } : item
            )
        );
    };
    
    const handleDeleteItem = (index: number) => {
        setActionItems(prevItems =>
            prevItems.map((item, i) =>
                i === index ? { ...item, isDeleting: true } : item
            )
        );
    };


    const tabConfig: { id: AnalysisTab; label: string; icon: React.ReactNode; hasContent: boolean }[] = useMemo(() => ([
        { id: 'summary', label: 'Summary', icon: <LightbulbIcon className="w-4 h-4" />, hasContent: !!response.summary },
        { id: 'obligations', label: 'Obligations', icon: <GavelIcon className="w-4 h-4" />, hasContent: (response.keyClauses?.length ?? 0) > 0 || (response.actionItems?.length ?? 0) > 0 },
        { id: 'flags', label: 'Red Flags', icon: <AlertTriangleIcon className="w-4 h-4" />, hasContent: (response.discrepancies?.length ?? 0) > 0 },
        { id: 'details', label: 'Details', icon: <FileTextIcon className="w-4 h-4" />, hasContent: (response.legalJargon?.length ?? 0) > 0 || (response.documentTypes?.length ?? 0) > 0 },
    ]), [response]);

    useEffect(() => {
        if (renderAllForPdf) return;
        const currentTabHasContent = tabConfig.find(t => t.id === activeTab)?.hasContent;
        if (!currentTabHasContent) {
            const firstAvailableTab = tabConfig.find(t => t.hasContent);
            if (firstAvailableTab && firstAvailableTab.id !== activeTab) {
                setActiveTab(firstAvailableTab.id);
            }
        }
    }, [activeTab, tabConfig, renderAllForPdf]);

    return (
        <div className="mt-6 animate-fade-in-up">
            <AnalysisActionsBar
                isSpeaking={isSpeaking}
                isPaused={isPaused}
                isExportingPdf={isExportingPdf}
                textSizer={textSizer}
                onPlayPause={handlePlayPause}
                onStop={handleStop}
                onExportPdf={handleExportPdf}
            />

            <div role="tablist" aria-label="Analysis Sections" className="flex border-b border-slate-700 bg-slate-900 overflow-x-auto">
                {tabConfig.map(tab => tab.hasContent && (
                    <button
                        key={tab.id}
                        id={`tab-${tab.id}`}
                        onClick={() => setActiveTab(tab.id)}
                        className={`flex items-center gap-2 px-4 py-3 text-sm font-semibold transition-colors border-b-2 flex-shrink-0 ${activeTab === tab.id ? 'border-amber-400 text-amber-400' : 'border-transparent text-gray-400 hover:text-white'}`}
                        role="tab"
                        aria-selected={activeTab === tab.id}
                        aria-controls={`panel-${tab.id}`}
                    >
                        {tab.icon}
                        {tab.label}
                    </button>
                ))}
            </div>
            
            <div ref={reportRef} className="p-6 bg-slate-900 border-x border-b border-slate-700 rounded-b-lg prose prose-invert max-w-none">
                {(activeTab === 'summary' || renderAllForPdf) && tabConfig[0].hasContent && (
                    <section id="panel-summary" role="tabpanel" aria-labelledby="tab-summary" className={renderAllForPdf ? 'mb-8' : ''}>
                        <SummaryPanel
                            summary={response.summary}
                            suggestedNextSteps={response.suggestedNextSteps}
                            strategicCommunication={response.strategicCommunication}
                            jurisdiction={jurisdiction}
                            strategicDraftEmail={editedStrategicEmail}
                            isStrategicEmailEditing={isStrategicEmailEditing}
                            isCopied={isCopied}
                            onToggleEdit={() => setIsStrategicEmailEditing(!isStrategicEmailEditing)}
                            onCopy={handleCopyStrategicEmail}
                            onDraftChange={setEditedStrategicEmail}
                        />
                    </section>
                )}
                 {(activeTab === 'obligations' || renderAllForPdf) && tabConfig[1].hasContent && (
                    <section id="panel-obligations" role="tabpanel" aria-labelledby="tab-obligations" className={renderAllForPdf ? 'mb-8' : ''}>
                        <ObligationsPanel
                            keyClauses={response.keyClauses}
                            actionItems={actionItems}
                            jurisdiction={jurisdiction}
                            onToggleComplete={handleToggleComplete}
                            onDelete={handleDeleteItem}
                        />
                    </section>
                )}
                {(activeTab === 'flags' || renderAllForPdf) && tabConfig[2].hasContent && (
                    <section id="panel-flags" role="tabpanel" aria-labelledby="tab-flags" className={`${renderAllForPdf ? 'mb-8' : ''}`}>
                        <FlagsPanel discrepancies={response.discrepancies} jurisdiction={jurisdiction} />
                    </section>
                )}
                {(activeTab === 'details' || renderAllForPdf) && tabConfig[3].hasContent && (
                    <section id="panel-details" role="tabpanel" aria-labelledby="tab-details" className={renderAllForPdf ? 'mb-8' : ''}>
                        <DetailsPanel
                            legalJargon={response.legalJargon}
                            documentTypes={response.documentTypes}
                            jurisdiction={jurisdiction}
                        />
                    </section>
                )}
                {((response.legalInsights && response.legalInsights.length > 0) || (response.actionItems?.length ?? 0) > 0) && (
                    <section className={renderAllForPdf ? 'mb-8' : ''}>
                        <h4 className="text-xl font-bold text-gray-200 mb-3 flex items-center gap-2"><GavelIcon className="text-amber-400 w-5 h-5" />Legal References</h4>
                        <AnalysisReferences
                            legalInsights={response.legalInsights ?? ''}
                            sources={response.actionItems?.map(a => a.source).filter(Boolean) ?? []}
                        />
                    </section>
                )}

                <div className={renderAllForPdf ? '' : 'pt-6 border-t border-slate-700/50 mt-8'}>
                    <p className="text-xs text-gray-500 italic">{disclaimerText}</p>
                    <div className="no-pdf">
                        <Feedback />
                    </div>
                </div>
            </div>
        </div>
    );
};

export default AnalysisResult;
