import React, { useRef, useState } from 'react';
import { useIncidentReportState, useIncidentReportActions } from '../../hooks/useIncidentReporter';
import { useTextToSpeech } from '../../hooks/useTextToSpeech';
import { useTextSizer } from '../../hooks/useTextSizer';
import { exportElementAsPDF, exportTextFile } from '../../utils/exportUtils';
import { getISODate, getFormattedDate } from '../../utils/dateUtils';
import { cleanReportForSpeech } from '../../utils/stringUtils';
import IncidentMarkdown from './IncidentMarkdown';

import AlertTriangleIcon from '../icons/AlertTriangleIcon';
import GavelIcon from '../icons/GavelIcon';
import UsersIcon from '../icons/UsersIcon';
import ReportActionsBar from './ReportActionsBar';
import ReportReferences from './ReportReferences';
import ReportFooterControls from './ReportFooterControls';
import IncidentHeaderBadges from './IncidentHeaderBadges';
import IncidentSection from './IncidentSection';


const severityStyles: { [key: string]: string } = {
    Low: 'bg-green-500/20 text-green-300 border-green-500/30',
    Medium: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    High: 'bg-red-500/20 text-red-300 border-red-500/30',
};

const ReportResult: React.FC = () => {
    const { reportResponse: report, incidentData } = useIncidentReportState();
    const { reset } = useIncidentReportActions();
    const reportRef = useRef<HTMLDivElement>(null);
    const { isSpeaking, isPaused, speak, cancel, pause, resume } = useTextToSpeech();
    const [isExportingPdf, setIsExportingPdf] = useState(false);
    const textSizer = useTextSizer();

    if (!report) {
        return (
            <div className="text-center p-4 text-gray-400">
                <p>No report data to display.</p>
            </div>
        );
    }

    const handleExportPdf = async () => {
        if (!reportRef.current) return;
        setIsExportingPdf(true);
        try {
            const isoDate = getISODate();
            const friendlyDate = getFormattedDate();
            const filename = `CustodyBuddy-Incident-Report-${isoDate}.pdf`;
            const headerText = `AI Incident Report - Generated by CustodyBuddy.com on ${friendlyDate}`;
            await exportElementAsPDF(reportRef.current, filename, headerText);
        } catch (error) {
            console.error("Failed to export PDF:", error);
            alert("Sorry, there was an issue creating the PDF. Please try again.");
        } finally {
            setIsExportingPdf(false);
        }
    };

    const handleExportTxt = () => {
        if (!report) return;
        const isoDate = getISODate();
        const filename = `CustodyBuddy-Incident-Report-${isoDate}.txt`;
        const content = `
CUSTODYBUDDY AI INCIDENT REPORT
Generated: ${getFormattedDate()}
Disclaimer: This document was created using artificial intelligence and is intended to provide helpful information. It is not a source of legal advice. We recommend that you verify the information for accuracy.

--- INCIDENT DETAILS ---
Title: ${report.title}
Category: ${report.category}
Severity: ${report.severity}
Justification: ${report.severityJustification}

--- PROFESSIONAL SUMMARY ---
${report.professionalSummary}

--- OBSERVED IMPACT ON CHILDREN ---
${report.observedImpact}

--- LEGAL INSIGHTS (JURISDICTION: ${incidentData.jurisdiction}) ---
${report.legalInsights}

--- LEGAL REFERENCES & SOURCES ---
- See attached references in the report.
        `;
        exportTextFile(content.trim(), filename);
    };

    const handlePlayPause = () => {
        if (!report) return;
        if (!isSpeaking) {
            speak(cleanReportForSpeech(report));
        } else if (isPaused) {
            resume();
        } else {
            pause();
        }
    };
    
    const handleStop = () => cancel();

    return (
        <div className="animate-fade-in-up max-w-5xl mx-auto">
            <div className="sr-only" role="status" aria-live="polite">Incident report generated.</div>
            <ReportActionsBar onReset={reset} textSizer={textSizer} />

            <div
                ref={reportRef}
                className="p-8 bg-slate-900 border-x border-b border-slate-700 rounded-b-lg prose prose-invert max-w-none space-y-10 leading-7 print:bg-white print:text-slate-900 print:prose-headings:text-slate-900 print:border print:border-slate-200 print:shadow-none print:leading-8 print:prose-invert:prose-headings:text-slate-900 print:prose-invert:prose-p:text-slate-900"
            >
                <IncidentHeaderBadges
                    title={report.title}
                    category={report.category}
                    severity={report.severity}
                    severityClass={severityStyles[report.severity]}
                    incidentDate={incidentData.incidentDate}
                    jurisdiction={incidentData.jurisdiction}
                    location={incidentData.location}
                    severityJustification={report.severityJustification}
                />
                
                <section className="space-y-10 divide-y divide-slate-800/70 print:divide-slate-200">
                    <IncidentSection title="Professional Summary" icon={<UsersIcon />}>
                        <IncidentMarkdown content={report.professionalSummary} className="max-w-3xl" />
                    </IncidentSection>
                    <IncidentSection title="Observed Impact on Children" icon={<AlertTriangleIcon className="text-yellow-400 w-5 h-5" />}>
                        <IncidentMarkdown content={report.observedImpact} jurisdiction={incidentData.jurisdiction} linkify className="max-w-3xl" />
                    </IncidentSection>
                    <IncidentSection title={`Legal Insights (${incidentData.jurisdiction})`} icon={<GavelIcon className="text-amber-400 w-5 h-5" />}>
                        <IncidentMarkdown content={report.legalInsights} jurisdiction={incidentData.jurisdiction} linkify className="max-w-3xl" />
                    </IncidentSection>
                    <ReportReferences legalInsights={report.legalInsights} sources={report.sources || []} />
                </section>
                
                <div className="pt-6 border-t border-slate-700/50 mt-8">
                    <p className="text-center md:text-left text-xs text-gray-500 italic">Disclaimer: This document was created using artificial intelligence and is intended to provide helpful information. It is not a source of legal advice. We recommend that you verify the information for accuracy.</p>
                    <ReportFooterControls
                        isSpeaking={isSpeaking}
                        isPaused={isPaused}
                        onPlayPause={handlePlayPause}
                        onStop={handleStop}
                        onExportTxt={handleExportTxt}
                        onExportPdf={handleExportPdf}
                        isExportingPdf={isExportingPdf}
                    />
                </div>
            </div>
        </div>
    );
};

export default React.memo(ReportResult);
